"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { Web3ReactProvider } from "@web3-react/core";
import { connectors } from "@/connectors";
const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Divine Aura Bliss",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Web3ReactProvider connectors={connectors}>
        <body className={inter.className}>{children}</body>
      </Web3ReactProvider>
    </html>
  );
}
